spring:
  application:
    name: redis_throughput

  data:
    redis:
      password: q1w2e3r4
      client-name: ${spring.application.name}
      url: redis://10.0.2.2:6379

server:
  port: 8099
  servlet:
    context-path: /api/throughput/v1

management:
  server:
    port: 8901
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true