spring:
  application:
    name: redis_throughput

  data:
    redis:
      host: localhost
      port: 6379
      password: q1w2e3r4
      lettuce:
        pool:
          max-active: 6
          max-idle: 6
          min-idle: 2
      client-name: ${spring.application.name}

server:
  port: 8099
  servlet:
    context-path: /api/throughput/v1

management:
  server:
    port: 8901
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true